mybatis:
  mapper-locations: classpath:com.lgl.qidian.mapper/**.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qidian?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-wait: 10
        min-idle: 1
        max-idle: 8
    port: 6379
  rabbitmq:
    virtual-host: /lgl
    username: lgl
    password: 1539450894
    host: 127.0.0.1
    port: 5672



db:
  table:
    one-table-num: "20000"

jwt.secret: "123456"







